groups:
  - name: app
    rules:
      - alert: ServiceDown
        expr: up{job="app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "FastAPI service has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency is {{ $value }} seconds"

      - alert: DatabaseSlowQueries
        expr: rate(prisma_slow_queries_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Database slow queries detected"
          description: "Slow query rate is {{ $value }} queries per second"

      - alert: HighMemoryUsage
        expr: system_memory_percent > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}MB"

      - alert: HighCPUUsage
        expr: system_cpu_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: DatabaseConnectionPoolExhausted
        expr: prisma_pool_connections_idle == 0 and prisma_pool_connections_busy > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool exhausted"
          description: "No idle database connections available"

  - name: infrastructure
    rules:
      - alert: LokiDown
        expr: up{job="loki"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Loki is down"
          description: "Loki has been down for more than 1 minute"

      - alert: TempoDown
        expr: up{job="tempo"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Tempo is down"
          description: "Tempo has been down for more than 1 minute"
