global:
  scrape_interval: '30s'
  evaluation_interval: '30s'

rule_files: []

scrape_configs:
  - job_name: 'app'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['app:8080']
