global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'application'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    scrape_timeout: 10s
    honor_labels: true
#
#  - job_name: 'prometheus'
#    static_configs:
#      - targets: ['localhost:9090']
#    scrape_interval: 15s
#    metrics_path: /metrics
#
#  - job_name: 'loki'
#    static_configs:
#      - targets: ['loki:3100']
#    scrape_interval: 15s
#    metrics_path: /metrics
#
#  - job_name: 'tempo'
#    static_configs:
#      - targets: ['tempo:3200']
#    scrape_interval: 15s
#    metrics_path: /metrics
#
#  - job_name: 'grafana'
#    static_configs:
#      - targets: ['grafana:3000']
#    scrape_interval: 30s
#    metrics_path: /metrics

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
#
#  - job_name: 'alertmanager'
#    static_configs:
#      - targets: ['alertmanager:9093']
#    scrape_interval: 15s
#    metrics_path: /metrics
