global:
  scrape_interval: '15s'
  evaluation_interval: '15s'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: app
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ["app:8080"]
