global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'obs-stack'
    replica: 'prometheus-1'

rule_files:
  - "/etc/prometheus/alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

storage:
  tsdb:

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    scrape_timeout: 10s
    honor_labels: true
    sample_limit: 10000
