global:
  scrape_interval: '15s'
  evaluation_interval: '15s'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 # If you add Alertmanager later

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'app'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['app:8080']
    exemplar_config:
      max_exemplars: 100
