global:
  scrape_interval: '15s'
  evaluation_interval: '15s'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 # If you add Alertmanager later

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'app'
    metrics_path: '/api/v1/metrics'
    honor_labels: true
    honor_timestamps: true
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        regex: '([^:]+)(?::\d+)?'
        target_label: instance
        replacement: '$1'
      - source_labels: [__metrics_path__]
        target_label: metrics_path
