auth_enabled: false

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 60m
  max_block_bytes: 1_000_000
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    # Add heartbeat timeout
    heartbeat_timeout: 1m

compactor:
  compaction:
    block_retention: 1h
    compacted_block_retention: 10m
  ring:
    kvstore:
      store: inmemory

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  max_concurrent_queries: 20
  search:
    query_timeout: 30s

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    max_duration: 0s
    # Add concurrent jobs
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true
        headers:
          X-Scope-OrgID: 1

  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
    service_graphs:
      histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
      dimensions: ['server.address', 'server.port']
      enable_client_server_prefix: true
    span_metrics:
      histogram_buckets: [0.002, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
      dimensions: ['http.method', 'http.status_code']
      enable_target_info: true

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: true
      max_active_series: 60000
      collection_interval: 5s
      disable_collection: false

usage_report:
  reporting_enabled: false
