auth_enabled: false

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_bytes: 5_242_880
  max_block_duration: 10m
  complete_block_timeout: 5m

compactor:
  compaction:
    block_retention: 168h

storage:
  trace:
    backend: local
    local: { path: /var/tempo/traces }
    wal:   { path: /var/tempo/wal }
    pool:
      max_workers: 100
      queue_depth: 10000

query_frontend:
  search:        { default_result_limit: 50, max_result_limit: 1000, max_duration: 12h }

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /var/tempo/generator
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
    service_graphs:
      histogram_buckets: [0.1,0.2,0.4,0.8,1.6,3.2,6.4,12.8]
      dimensions: [http.method,http.target,http.status_code,service.version]
      peer_attributes: [http.method,http.target,http.status_code,service.version]
      enable_client_server_prefix: true
    span_metrics:
      histogram_buckets: [0.002,0.005,0.01,0.025,0.05,0.075,0.1,0.25,0.5,0.75,1,2.5,5,7.5,10]
      dimensions: [http.method,http.target,http.status_code,service.version]
      enable_target_info: true

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
