auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_bytes: 5_242_880
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 168h

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

query_frontend:
  search:
    default_result_limit: 50

metrics_generator:
  storage:
    path: /var/tempo/generator
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    service_graphs:
    span_metrics:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
