auth_enabled: false

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 60m
  max_block_bytes: 1_000_000
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    # Add heartbeat timeout
    heartbeat_timeout: 1m

compactor:
  compaction:
    block_retention: 168h
  ring:
    kvstore:
      store: inmemory

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
    wal:
      path: /var/tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  max_concurrent_queries: 20
  search:
    query_timeout: 30s

query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    max_duration: 0s
    # Add concurrent jobs
    concurrent_jobs: 1000
    target_bytes_per_job: 104857600

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: application
    collection_interval: 15s
  storage:
    path: /var/tempo/generator
  traces_storage:
    path: /var/tempo/generator/traces
  processor:
    local_blocks:
      filter_server_spans: false
      flush_to_storage: true
    service_graphs:
      histogram_buckets: [0.1, 0.2, 0.4, 0.8, 1.6, 3.2, 6.4, 12.8]
      dimensions: ['http.method', 'http.target', 'http.status_code', 'service.version']
      peer_attributes: ['db.name', 'db.operation', 'http.method', 'http.target', 'http.status_code', 'service.version']
      enable_client_server_prefix: true
    span_metrics:
      histogram_buckets: [0.002, 0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0]
      dimensions: ['http.method', 'http.target',' http.status_code', 'service.version']
      enable_target_info: true
      intrinsic_dimensions:
        service: true
        span_kind: true
        span_name: true
        status_code: true

overrides:
  ingestion_rate_strategy: local
  ingestion_rate_limit_bytes: 20000000
  ingestion_burst_size_bytes: 30000000
  max_search_duration: 0s
  max_bytes_per_tag_values_query: 5000000
  max_blocks_per_tag_values_query: 100
  max_traces_per_user: 10000
  max_global_traces_per_user: 0
  max_bytes_per_trace: 5000000
  block_retention: 24h
  forwarders: []
  metrics_generator_ring_size: 1
  metrics_generator_max_active_series: 10000
  metrics_generator_collection_interval: 15s
  metrics_generator_disable_collection: false
  metrics_generator_forwarder_queue_size: 100
  metrics_generator_processors: [service-graphs, span-metrics, local-blocks]
  per_tenant_override_period: 10s

usage_report:
  reporting_enabled: false
