apiVersion: 1

datasources:
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          matcherType: regex
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
