apiVersion: 1

datasources:
  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo:3200
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        customQuery: false
        datasourceUid: loki
        filterBySpanID: false
        filterByTraceID: true
        tags:
          - key: service.name
            value: compose_service
    readOnly: false
    editable: true
