apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  uid: tempo
  editable: true
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
    nodeGraph:
      enabled: true
    search:
      hide: false
    tracesToLogs:
      datasourceUid: loki
      tags: ['job', 'instance', 'pod', 'namespace', 'service.name']
      mappedTags: [{ key: 'service.name', value: 'compose_service' }]
      mapTagNamesEnabled: true
      spanStartTimeShift: '-1m'
      spanEndTimeShift: '1m'
      filterByTraceID: true
      filterBySpanID: true
    tracesToMetrics:
      datasourceUid: prometheus
      tags: [{ key: 'service.name', value: 'compose_service' }]
      queries:
        - name: 'Sample query'
          query: 'sum(rate(http_request_duration_seconds_count{service="$${__tags.service.name}"}[5m]))'
    lokiSearch:
      datasourceUid: loki
  version: 1
