name: "fastapi-starter"

services:
  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: "unless-stopped"
    environment:
      DISABLE_IPV6: "true"
    networks:
      - "proxy"
    ports:
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
    volumes:
      - "./proxy/data:/data"
      - "./proxy/letsencrypt:/etc/letsencrypt"
    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: "10s"
      timeout: "3s"

  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
      target: "build-dev"  # TODO: Change to "build" later
    depends_on:
      - "redis"
      - "postgres"
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      TZ: "${TZ}"
    networks:
      - "proxy"
      - "deps"
    restart: "unless-stopped"
    volumes:
      - ".:/app"
    command: "/start.sh app"

  worker:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
      target: "build"
    depends_on:
      - "app"
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      TZ: "${TZ}"
    networks:
      - "deps"
    restart: "unless-stopped"
    command: "/start.sh worker"

  scheduler:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
      target: "build"
    depends_on:
      - "app"
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      TZ: "${TZ}"
    networks:
      - "deps"
    restart: "unless-stopped"
    command: "/start.sh scheduler"

  postgres:
    image: "bitnami/postgresql:latest"
    environment:
      POSTGRES_USER: "${POSTGRESQL_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRESQL_DATABASE: "${POSTGRESQL_DATABASE}"
      TZ: "${TZ}"
    networks:
      - "deps"
    ports:  # TODO: Remove later
      - "5432:5432"
    restart: "unless-stopped"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  redis:
    image: "bitnami/redis:latest"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      TZ: "${TZ}"
    networks:
      - "deps"
    restart: "unless-stopped"
    volumes:
      - "redis_data:/data"

  parseable:
    image: containers.parseable.com/parseable/parseable:latest
    environment:
      P_USERNAME: ${PARSEABLE_USERNAME}
      P_PASSWORD: ${PARSEABLE_PASSWORD}
      P_FS_DIR: "/parseable/data"
      P_STAGING_DIR: "/parseable/staging"
      TZ: "${TZ}"
    networks:
      - "proxy"
      - "deps"
    restart: "unless-stopped"
    volumes:
      - "parseable_data:/parseable"
    command: "parseable local-store"

volumes:
  postgres_data:
  seq_data:
  redis_data:
  parseable_data:

networks:
  proxy:
    external: true
    name: "proxy"
  deps:
    external: true
    name: "deps"
