name: "fastapi-starter-observability"

services:
  loki:
    image: "grafana/loki"
    container_name: "loki"
    volumes:
      - "./conf/grafana/loki-config.yml:/etc/loki/local-config.yaml"
      - "loki_data:/loki"
    networks:
      - "obs-tier"
    restart: "unless-stopped"
    command: "-config.file=/etc/loki/local-config.yaml"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: "5"

  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "./conf/grafana/datasources:/etc/grafana/provisioning/datasources"
    networks:
      - "proxy-tier"
      - "obs-tier"
    restart: "unless-stopped"
    depends_on:
      loki:
        condition: "service_healthy"

networks:
  proxy-tier:
    name: "proxy-tier"
    driver: "bridge"
  obs-tier:
    name: "obs-tier"
    driver: "bridge"

volumes:
  loki_data:
  grafana_data:
