name: "fastapi-starter"

services:
  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
      target: "build-dev"  # TODO: Change to "build" later
    container_name: "app"
    depends_on:
      postgres:
        condition: "service_healthy"
      redis:
        condition: "service_healthy"
      grafana:
        condition: "service_healthy"
    env_file:
      - ".env"
    networks:
      - "proxy-tier"
      - "infra-tier"
      - "obs-tier"
    restart: "unless-stopped"
    volumes:
      - ".:/app"

networks:
  proxy-tier:
    name: "proxy-tier"
    driver: "bridge"
  infra-tier:
    name: "infra-tier"
    driver: "bridge"
  obs-tier:
    name: "obs-tier"
    driver: "bridge"

include:
  - "docker-compose.deps.yml"
  - "docker-compose.grafana.yml"
