name: "fastapi-starter"

services:
  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
      target: "build-dev"  # TODO: Change to "build" later
    container_name: "app"
    depends_on:
      nginx-proxy:
        condition: "service_healthy"
      postgres:
        condition: "service_healthy"
      redis:
        condition: "service_healthy"
      grafana:
        condition: "service_healthy"
    env_file:
      - ".env"
    networks:
      - "proxy-tier"
      - "infra-tier"
      - "obs-tier"
    restart: "unless-stopped"
    volumes:
      - ".:/app"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/health/liveness"]
      interval: "30s"
      timeout: "10s"
      retries: "3"
      start_period: "60s"
    labels:
      - "compose_service=app"
      - "logging=lokifluent"

networks:
  proxy-tier:
    name: "proxy-tier"
    driver: "bridge"
  infra-tier:
    name: "infra-tier"
    driver: "bridge"
  obs-tier:
    name: "obs-tier"
    driver: "bridge"

include:
  - "docker-compose.deps.yml"
  - "docker-compose.grafana.yml"
