services:
  loki:
    image: "grafana/loki:3.5.1"
    container_name: "loki"
    volumes:
      - "./conf/grafana/loki-config.yml:/etc/loki/local-config.yaml"
      - "loki_data:/loki"
    networks:
      - "obs-tier"
    restart: "unless-stopped"
    command: "-config.file=/etc/loki/local-config.yaml"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
      start_period: "30s"

  tempo:
    image: "grafana/tempo:2.8.1"
    container_name: "tempo"
    volumes:
      - "./conf/grafana/tempo-config.yml:/etc/tempo/tempo.yml"
      - "tempo_data:/var/tempo"
    networks:
      - "obs-tier"
    restart: "unless-stopped"
    command: ["-config.file=/etc/tempo/tempo.yml"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3200/ready"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
      start_period: "30s"

  prometheus:
    image: "prom/prometheus:v2.53.5"
    container_name: "prometheus"
    volumes:
      - "./conf/grafana/prometheus-config.yml:/etc/prometheus/prometheus.yml"
      - "./conf/grafana/alert-rules.yml:/etc/prometheus/alert-rules.yml"
      - "prometheus_data:/prometheus"
    restart: "unless-stopped"
    networks:
      - "obs-tier"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=exemplar-storage'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "-q", "http://localhost:9090/-/ready"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
      start_period: "30s"

  node-exporter:
    image: "prom/node-exporter:v1.8.2"
    container_name: "node-exporter"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    restart: "unless-stopped"
    networks:
      - "obs-tier"
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "-q", "http://localhost:9100/metrics"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
      start_period: "30s"

  alertmanager:
    image: "prom/alertmanager:v0.28.1"
    container_name: "alertmanager"
    volumes:
      - "./conf/grafana/alertmanager.yml:/etc/alertmanager/alertmanager.yml"
    restart: "unless-stopped"
    networks:
      - "obs-tier"
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "-q", "http://localhost:9093/-/ready"]
      interval: "10s"
      timeout: "5s"
      retries: "5"
      start_period: "30s"

  grafana:
    image: "grafana/grafana"
    container_name: "grafana"
    depends_on:
      loki:
        condition: "service_healthy"
      tempo:
        condition: "service_healthy"
      prometheus:
        condition: "service_healthy"
      node-exporter:
        condition: "service_healthy"
      alertmanager:
        condition: "service_healthy"
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_FEATURE_TOGGLES_ENABLE: "traceqlEditor"
    volumes:
      - "./conf/grafana/provisioning:/etc/grafana/provisioning"
      - "./conf/grafana/dashboards:/etc/grafana/dashboards"
      - "grafana_data:/var/lib/grafana"
    networks:
      - "proxy-tier"
      - "obs-tier"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: "5"

networks:
  proxy-tier:
    name: "proxy-tier"
    driver: "bridge"
  obs-tier:
    name: "obs-tier"
    driver: "bridge"

volumes:
  loki_data:
  tempo_data:
  prometheus_data:
  grafana_data:
