name: "fastapi-starter"

services:
  app:
    build:
      context: ".."
      dockerfile: ".devcontainer/Dockerfile"
      target: "build-dev"  # TODO: Change to "build" later
    depends_on:
      - "redis"
      - "postgres"
      - "otel-collector"
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      TZ: "${TZ}"
      OTEL_SERVICE_NAME: "fastapi-starter"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    networks:
      - "app-tier"
      - "infra-tier"
      - "otel-tier"
    restart: "unless-stopped"
    volumes:
      - ".:/app"
    command: "/start.sh app"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: "30s"
      timeout: "10s"
      retries: "3"
      start_period: "60s"
#
#  worker:
#    build:
#      context: ".."
#      dockerfile: ".devcontainer/Dockerfile"
#      target: "build"
#    depends_on:
#      - "redis"
#      - "postgres"
#      - "otel-collector"
#    environment:
#      ENVIRONMENT: "${ENVIRONMENT}"
#      TZ: "${TZ}"
#    networks:
#      - "infra-tier"
#      - "otel-tier"
#    restart: "unless-stopped"
#    command: "/start.sh worker"
#
#  scheduler:
#    build:
#      context: ".."
#      dockerfile: ".devcontainer/Dockerfile"
#      target: "build"
#    depends_on:
#      - "redis"
#      - "postgres"
#      - "otel-collector"
#    environment:
#      ENVIRONMENT: "${ENVIRONMENT}"
#      TZ: "${TZ}"
#    networks:
#      - "infra-tier"
#      - "otel-tier"
#    restart: "unless-stopped"
#    command: "/start.sh scheduler"

networks:
  app-tier:
    name: "app-tier"
    driver: bridge
  infra-tier:
    name: "infra-tier"
    driver: bridge
  otel-tier:
    name: "otel-tier"
    driver: bridge

include:
  - docker-compose.deps.yml
  - docker-compose.otel.yml
